apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-configmap
  namespace: sentinel-system
data:
  SPRING_PROFILES_ACTIVE: "production"
  POSTGRES_HOST: "sentinel-postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "sentinel_db"
  REDIS_HOST: "sentinel-redis"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "sentinel-kafka:9092"
  SENTINEL_ALLOWED_ORIGINS: "https://sentinel.enterprise.com"
