apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentinel-postgres-pvc
  namespace: sentinel-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
