package com.sentinel.common.security;

public enum SecurityEventType {
    USER_REGISTERED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    LOGOUT,
    TOKEN_REFRESHED,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    EMAIL_VERIFICATION_REQUESTED,
    AUTHORIZATION_FAILURE,
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    PERMISSION_CREATED,
    PERMISSION_UPDATED,
    PERMISSION_DELETED
}

