apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: sentinel-system
spec:
  type: ClusterIP
  selector:
    app: gateway-service
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: sentinel-system
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ai-engine
  namespace: sentinel-system
spec:
  type: ClusterIP
  selector:
    app: ai-engine
  ports:
    - port: 8000
      targetPort: 8000
