package com.sentinel.threat.domain.model;

public enum ThreatType {
    SQL_INJECTION,
    XSS,
    PATH_TRAVERSAL,
    COMMAND_INJECTION,
    RCE,
    JWT_MANIPULATION,
    TOKEN_REPLAY,
    BROKEN_AUTH,
    BROKEN_AUTHZ,
    API_ENUMERATION,
    EXCESSIVE_REQUESTS,
    BRUTE_FORCE,
    CREDENTIAL_STUFFING,
    SUSPICIOUS_USER_AGENT,
    BOT_DETECTION,
    METHOD_ABUSE,
    INVALID_CONTENT_TYPE,
    HEADER_MANIPULATION
}
